remote_theme: pmarsceill/just-the-docs

classes: wide

search_enabled: true

title: 'SQLFlow'

ga_tracking: UA-17331483-8

aux_links:
  "GitHub":
    - "https://github.com/sql-machine-learning/sqlflow"

exclude: ['*.sql', '*.go', '.gitignore', '*.sh', '*.proto', '*.y']

# baseurl: "/sql-machine-learning.github.io/"

defaults:
  - scope:
      path: "sqlflow"
    values:
      layout: "doc"
      nav_exclude: true
      grand_parent: SQLFlow
      prefix: '/sqlflow/'
  - scope:
      path: "sqlflow/doc/installation.md"
    values:
      nav_exclude: false
      parent: SQLFlow
      nav_order: 1
  - scope:
      path: "sqlflow/doc/syntax.md"
    values:
      nav_exclude: false
      parent: Design
  - scope:
      path: "sqlflow/doc/walkthrough.md"
    values:
      nav_exclude: false
      parent: Design
  - scope:
      path: "sqlflow/doc/sql_parser.md"
    values:
      nav_exclude: false
      parent: Design
  - scope:
      path: "sqlflow/doc/database_abstraction_layer.md"
    values:
      nav_exclude: false
      parent: Design
  - scope:
      path: "sqlflow/doc/pipe.md"
    values:
      nav_exclude: false
      parent: Design
  - scope:
      path: "sqlflow/doc/build.md"
    values:
      nav_exclude: false
      parent: Contribute
  - scope:
      path: "sqlflow/doc/build-tensorflow.md"
    values:
      nav_exclude: false
      parent: Contribute
  - scope:
      path: "sqlflow/doc/mysql-setup.md"
    values:
      nav_exclude: false
      parent: Contribute
  - scope:
      path: "sqlflow/doc/close_producer_from_consumer.md"
    values:
      nav_exclude: false
      parent: Contribute
  - scope:
      path: "sqlflow/doc/submitter.md"
    values:
      nav_exclude: false
      parent: Contribute
  - scope:
      path: "pysqlflow"
    values:
      prefix: '/pysqlflow/'
  - scope:
      path: "pysqlflow/doc/desigin/client_design_doc.md"
    values:
      nav_exclude: false
      parent: PySQLFlow
  - scope:
      path: "pysqlflow/doc/desigin/magic_design_doc.md"
    values:
      nav_exclude: false
      parent: PySQLFlow
  - scope:
      path: "gomaxcompute"
    values:
      layout: doc
      parent: GoMaxCompute
  - scope:
      path: "gohive"
    values:
      layout: doc
      parent: GoHive
      prefix: '/gohive/'


  - scope:
      path: "elasticdl"
    values:
      nav_exclude: true
      prefix: '/elasticdl'
  - scope:
      path: "elasticdl/elasticdl/doc/overview.md"
    values:
      nav_exclude: false
      parent: ElasticDL
  - scope:
      path: "elasticdl/elasticdl/doc/worker_optimization_design.md"
    values:
      nav_exclude: false
      parent: ElasticDL
  - scope:
      path: "elasticdl/elasticdl/doc/odps_support_design.md"
    values:
      nav_exclude: false
      parent: ElasticDL
  - scope:
      path: "elasticdl/elasticdl/doc/model_evaluation_design.md"
    values:
      nav_exclude: false
      parent: ElasticDL
  - scope:
      path: "elasticdl/elasticdl/doc/model_building.md"
    values:
      nav_exclude: false
      parent: ElasticDL
  - scope:
      path: "elasticdl/elasticdl/doc/high-level-api.md"
    values:
      nav_exclude: false
      parent: ElasticDL
  - scope:
      path: "elasticdl/elasticdl/doc/elastic_sync_sgd.md"
    values:
      nav_exclude: false
      parent: ElasticDL
  - scope:
      path: "elasticdl/elasticdl/doc/elastic_scheduling.md"
    values:
      nav_exclude: false
      parent: ElasticDL
  - scope:
      path: "elasticdl/elasticdl/doc/distributed_embedding_layer_design.md"
    values:
      nav_exclude: false
      parent: ElasticDL
  - scope:
      path: "elasticdl/elasticdl/doc/data_preparation_design.md"
    values:
      nav_exclude: false
      parent: ElasticDL
  - scope:
      path: "elasticdl/elasticdl/doc/distributed_embedding_layer_design.md"
    values:
      nav_exclude: false
      parent: ElasticDL


  

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sql-machine-learning"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
